# -*- coding: utf-8 -*-
"""dig_reg_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YpV0QhjlqT_kYNvmAVgc690L5JSv904
"""




import streamlit as st
import numpy as np
import tensorflow as tf
from PIL import Image , ImageOps

st.title("Digit Recognotion using CNN")
st.write("Upload an image of a digit (28*28 Gray Scale)")
model = tf.keras.models.load_model('digit_model.keras')
uploaded_file = st.file_uploader("Choose a file" , type="jpg")
if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('L')
    image = ImageOps.invert(image)
    image = image.resize((28,28))
    img_array = np.array(image)
    img_array = img_array.reshape(-1,28,28,1)
    img_array = img_array.astype('float32')
    img_array /= 255.0
    st.image(image, caption='Uploaded Image', use_column_width=True)
    prediction = model.predict(img_array)
    st.success(f'The predicted digit is {np.argmax(prediction)}')
